export const SAFE_PLAYER_SELECT = {
  id:                 true,
  username:           true,
  email:              true,
  maxXp:              true,
  totalCoins:         true,
  maxHp:              true,
  isAdmin:            true,
  isMuted:            true,
  authProvider:       true,
  firstLogin:         true,
  lastLogin:          true,
  totalGamesPlayed:   true,
  totalEnemiesKilled: true,
  bulletDamage:       true,
  fireRate:           true,
  reloadTime:         true,
  hasNoReload:        true,
  magSize:            true,
  staminaPool:        true,
  staminaRegen:       true,
} as const;
