DROP DATABASE IF EXISTS catcafe_db;
CREATE DATABASE IF NOT EXISTS catcafe_db;
USE catcafe_db;

-- Days Table
CREATE TABLE days (
    day_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    day_name VARCHAR(20) NOT NULL,
    PRIMARY KEY (day_id),
    UNIQUE KEY uq_day_name (day_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Menu Items Table
CREATE TABLE menu_items (
    item_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    item_name VARCHAR(100) NOT NULL,
    item_description TEXT,
    image_url VARCHAR(500),
    category VARCHAR(50),
    PRIMARY KEY (item_id),
    UNIQUE KEY uq_item_name (item_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Menu for the Day Intermediate Table
CREATE TABLE day_menu (
    day_id SMALLINT UNSIGNED NOT NULL,
    item_id SMALLINT UNSIGNED NOT NULL,
    display_order INT NOT NULL DEFAULT 1,
    PRIMARY KEY (day_id, item_id),
    FOREIGN KEY (day_id) REFERENCES days(day_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (item_id) REFERENCES menu_items(item_id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Cats Table
CREATE TABLE cats (
    cat_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    cat_name VARCHAR(50) NOT NULL,
    age_label VARCHAR(50),
    personality TEXT,
    story TEXT,
    image_url VARCHAR(500),
    instagram_post_url VARCHAR(500),
    adoption_status ENUM('Adoptable', 'Adoptado', 'En Prueba') NOT NULL DEFAULT 'Adoptable',
    PRIMARY KEY (cat_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



-- SEED DATA
----------------------------------

-- Insert Days of the Week
INSERT INTO days (day_name) VALUES 
('lunes'), 
('martes'), 
('miércoles'), 
('jueves'), 
('viernes'), 
('sábado'), 
('domingo');


-- Insert Menu Items (generated by ChatGPT)
INSERT INTO menu_items (item_name, item_description, image_url, category) VALUES
('Strawberry Latte', 'Bebida dulce de fresa con leche espumosa.', 'https://afullliving.com/wp-content/uploads/2024/05/Strawberry-Latte-Reshoot-15.jpg?w=700', 'Bebida'),
('Cat Paw Pancakes', 'Hotcakes inspirados en huellitas de gato.', 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=700', 'Postre'),
('Salmon Toast', 'Tostada salada con salmón y aderezo.', 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=700', 'Comida'),

('Vanilla Cappuccino', 'Cappuccino suave con toque de vainilla.', 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=700', 'Bebida'),
('Blueberry Muffin', 'Muffin esponjoso con arándanos.', 'https://images.unsplash.com/photo-1607958996333-41aef7caefaa?w=700', 'Postre'),
('Tuna Sandwich', 'Sándwich fresco de atún.', 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=700', 'Comida'),

('Matcha Milk Tea', 'Té con matcha y leche cremosa.', 'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=700', 'Bebida'),
('Cat Face Cookies', 'Galletas decoradas con caritas de gato.', 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=700', 'Postre'),
('Chicken Wrap', 'Wrap ligero de pollo.', 'https://images.unsplash.com/photo-1539252554453-80ab65ce3586?w=700', 'Comida'),

('Caramel Frappe', 'Frappé frío con caramelo.', 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=700', 'Bebida'),
('Cheesecake Slice', 'Rebanada de cheesecake.', 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=700', 'Postre'),
('Ham Croissant', 'Croissant relleno de jamón.', 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=700', 'Comida'),

('Mocha Coffee', 'Café moka con chocolate.', 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=700', 'Bebida'),
('Chocolate Donut', 'Dona de chocolate.', 'https://caitsplate.com/wp-core/wp-content/uploads/2020/02/IMG_9022.jpg?w=700', 'Postre'),
('Avocado Toast', 'Tostada con aguacate.', 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=700', 'Comida'),

('Iced Rose Latte', 'Latte frío con notas florales.', 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=700', 'Bebida'),
('Berry Waffles', 'Waffles con frutos rojos.', 'https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?w=700', 'Postre'),
('Club Sandwich', 'Sándwich club clásico.', 'https://images.unsplash.com/photo-1553909489-cd47e0907980?w=700', 'Comida'),

('Hot Chocolate', 'Chocolate caliente espeso.', 'https://images.unsplash.com/photo-1517578239113-b03992dcdd25?w=700', 'Bebida'),
('Cinnamon Roll', 'Rol de canela glaseado.', 'https://dairyfarmersofcanada.ca/sites/default/files/styles/recipe_image/public/image_file_browser/conso_recipe/2025/cinnamon-roll.png.jpeg?itok=-J3QFZni?w=700', 'Postre'),
('Brunch Omelette', 'Omelette para brunch.', 'https://images.unsplash.com/photo-1510693206972-df098062cb71?w=700', 'Comida');

-- Insert Day Menu (assigning 3 items to each day)
INSERT INTO day_menu (day_id, item_id, display_order) VALUES
(1, 1, 1), (1, 2, 2), (1, 3, 3),
(2, 4, 1), (2, 5, 2), (2, 6, 3),
(3, 7, 1), (3, 8, 2), (3, 9, 3),
(4, 10, 1), (4, 11, 2), (4, 12, 3),
(5, 13, 1), (5, 14, 2), (5, 15, 3),
(6, 16, 1), (6, 17, 2), (6, 18, 3),
(7, 19, 1), (7, 20, 2), (7, 21, 3);

-- Insert Cats
INSERT INTO cats (cat_name, age_label, personality, story, image_url, instagram_post_url, adoption_status) VALUES
('Porthas', '1 año aprox.', 'Cariñoso y esperanzado.', 'Rescatado junto con sus hermanas; aún busca hogar.', 'Porthas_591620412_17973529061976589_4784377128203859139_n.jpg', 'https://www.instagram.com/p/DSdOZ7HCVAc/', 'Adoptable'),
('Frida', '1 año aprox.', 'Dulce y cariñosa.', 'Rescatada de situación de calle; ahora está segura.', 'Frida_649157267_18070838003556628_7137388871436600779_n.jpg', 'https://www.instagram.com/p/DVrLZzHjRTg/', 'Adoptable'),
('Guero', 'Más de 1 año aprox.', 'Amoroso e inteligente.', 'Fue rescatado, se perdió y logró volver a su hogar temporal.', 'Guero_657806657_17984156921976589_7985769081944850271_n.jpg', 'https://www.instagram.com/p/DWME82iAN0F/', 'Adoptable'),
('Nancy', 'Más de 1 año aprox.', 'Tranquila y cariñosa.', 'Busca una familia que la ame y la consienta mucho.', 'Nancy_540681917_17961681446976589_2680251941435619821_n.jpg', 'https://www.instagram.com/p/DOCyWUZAL5g/', 'Adoptable'),
('Lucy', '2 años aprox.', 'Tierna y sociable.', 'Fue rescatada de malas condiciones y hoy ya fue adoptada.', 'Lucy_486492272_17943975866976589_5452623100164383367_n.jpg', 'https://www.instagram.com/p/DHtwhD0SOcQ/', 'Adoptado');