import Phaser from "phaser";

export class InstructionScene extends Phaser.Scene {
    private scrollContainer!: Phaser.GameObjects.Container;
    private scrollMask!: Phaser.Display.Masks.GeometryMask;
    private contentHeight: number = 0;

    constructor() {
        super({ key: 'InstructionScene' });
    }

    create() {
        const { width, height } = this.cameras.main;
        const centerX = width / 2;
        const centerY = height / 2;
        this.input.enabled = true;

        this.cameras.main.setBackgroundColor('#1a1a1a');

        const bgWidth = width * 0.8;
        const bgHeight = height * 0.7;
        const bgX = centerX - bgWidth / 2;
        const bgY = 120;

        //background plate
        const bgGraphics = this.add.graphics();
        bgGraphics.fillStyle(0x333333, 0.9);
        bgGraphics.fillRoundedRect(bgX, bgY, bgWidth, bgHeight, 10);
        bgGraphics.lineStyle(4, 0x666666);
        bgGraphics.strokeRoundedRect(bgX, bgY, bgWidth, bgHeight, 10);

        //Tittle
        this.add.text(centerX, 60, 'HOW TO PLAY', {
            fontFamily: 'Impact', fontSize: '42px', color: '#acacac', stroke: '#000', strokeThickness: 6
        }).setOrigin(0.5);

        // Scrollable content container
        this.scrollContainer = this.add.container(bgX + 20, bgY + 20);

        let yOffset = 0;

        const contentWidth = bgWidth * 0.75;
        const contentX = (bgWidth - contentWidth) / 2;

        const createSection = (title: string, content: string, color = '#acacac') => {
            //Titulo centrado
            const titleText = this.add.text(bgWidth / 2, yOffset, title, {
                fontFamily: 'Impact, Arial',
                fontSize: '26px',
                color: '#ffcc00',
                stroke: '#000',
                strokeThickness: 4
            }).setOrigin(0.5, 0);

            yOffset += titleText.height + 10;

            const contentText = this.add.text(bgWidth / 2, yOffset, content, {
                fontFamily: 'Impact, Arial',
                fontSize: '18px',
                color: color,
                stroke: '#000',
                strokeThickness: 2,
                wordWrap: { width: contentWidth }, // content width padding
                align: 'center'
            }).setOrigin(0.5, 0);

            contentText.setLineSpacing(8);

            yOffset += contentText.height + 35;

            this.scrollContainer.add([titleText, contentText]);
        };

        //instructions text (ahora por secciones)
        createSection("THE MISSION",
        `Florida Frenzy is a 2D roguelite where TCG strategy meets fast-paced platforming. \nAs a member of the Crock Clan, you must explore the swamps, build your deck, and defeat powerful bosses.`);

        createSection("GENERAL CONTROLS",
        `- [A] [D]: Move Left and Right \n- [W] [SPACE]: Jump (Double Jump) \n- [E]: Interact \n- [I]: Open Inventory and Close Inventory \n- [ESC]: Pause \n- [MOUSE MOVEMENT]: Aim \n- [LEFT CLICK]: Shoot and and select/play cards\n (Double click for confirmation and select card) \n- [RIGHT CLICK]: Discard Card`);

        createSection("GAME FLOW",
        `Explore the map, avoid enemies and reach bosses. When you encounter a boss, a card duel begins. \nWin duels to earn rewards and improve your deck. Repeat this cycle to progress through the run.`);

        createSection("CARD DUEL RULES",
        `Each turn, play a card from your hand. \n\nA card is valid if it matches: \n- The SAME ELEMENT \n- The SAME NUMBER \n\nExamples: \nFire 5 → Fire 8 (valid) \nWater 4 → Sand 4 (valid) \n\nIf you can't play a card, you must draw from your deck.`);

        createSection("ENERGY SYSTEM",
        `There are two types of energy: \nElemental Energy: Generated by playing cards of the same element in a row. \nInstinct Energy: Generated based on the number of the card played. \n\nUse energy to activate powerful effects and abilities.`);

        createSection("CARD TYPES",
        `Fire: Deals direct damage. \nWater: Generates shield. \nSwamp: Applies poison over time. \nSand: Reduces incoming damage. \nIce: Rare cards that act as wildcards or special effects.`);

        createSection("ROGUELITE SYSTEM",
    `Each run is different. \n\nIf you lose, you restart from the beginning, but you keep your progress: \n- Experience (Swamp XP) \n- Unlocked cards \n- Clan Rank \n\nEvery run makes you stronger.`);
        

        this.contentHeight = yOffset;
        const maskShape = this.make.graphics();
        maskShape.fillStyle(0xffffff);
        maskShape.fillRoundedRect(bgX, bgY, bgWidth, bgHeight, 10);
        this.scrollMask = maskShape.createGeometryMask();
        this.scrollContainer.setMask(this.scrollMask);

        // 5. scroll logic
        this.input.on('wheel', (pointer: any, gameObjects: any, deltaX: number, deltaY: number) => {
            this.scrollContainer.y -= deltaY * 0.5; //scroll más suave
            this.limitScroll(bgY + 20, bgHeight);
        });

        // back to menu button
        this.createMetalBtn(centerX, height - 50, 250, 50, 'BACK TO MENU', () => {
            this.scene.start('MenuScene');
        });
    }

    private limitScroll(startY: number, bgHeight: number) {
        // limit scroll between the top of the content and the bottom of the content minus the visible area
        const minHeight = startY - (this.contentHeight - bgHeight + 40);
        if (this.scrollContainer.y > startY) this.scrollContainer.y = startY;
        if (this.scrollContainer.y < minHeight) this.scrollContainer.y = minHeight;
    }

    createMetalBtn(x: number, y: number, w: number, h: number, label: string, callback: () => void) {
        const container = this.add.container(x, y);
        const graphics = this.add.graphics();
        
        const draw = (pressed: boolean) => {
            graphics.clear();
            graphics.fillStyle(0x000000, 0.4);
            graphics.fillRoundedRect(-w/2 + 3, -h/2 + 3, w, h, 6);
            graphics.fillStyle(pressed ? 0x222222 : 0x444444, 1);
            graphics.fillRoundedRect(-w/2, -h/2, w, h, 4);
            graphics.fillStyle(pressed ? 0x333333 : 0x999999, 1);
            graphics.fillRect(-w/2 + 4, -h/2 + 4, w - 8, h/2 - 4);
            graphics.fillStyle(pressed ? 0x111111 : 0x666666, 1);
            graphics.fillRect(-w/2 + 4, 0, w - 8, h/2 - 4);
        };

        draw(false);
        const text = this.add.text(0, 0, label, {
            fontFamily: 'Impact', fontSize: '20px', color: '#fff', stroke: '#000', strokeThickness: 3
        }).setOrigin(0.5);

        container.add([graphics, text]);
        container.setSize(w, h).setInteractive({ useHandCursor: true })
            .on('pointerdown', () => { draw(true); text.y = 2; })
            .on('pointerup', () => { draw(false); text.y = 0; callback(); })
            .on('pointerout', () => { draw(false); text.y = 0; });
    }
}